
tmp_log_path_def=${TEMP_DIR}/to_del/exported_config_from_amodel_$(hostname).sh
[[ -d "./cmds" ]] && tmp_log_path_def="$(pwd -L)/cmds/ienv_$envMode.ini"
# using paramter will cause exception in transfer all paramters to the subshell
# e.g. overwite the file in loadbd or load cmd
# tmp_log_path="${1:-${tmp_log_path_def}}"
tmp_log_path=$tmp_log_path_def

(
bash_script_i
echo  "# $(date "+%Y%m%d_%H%M") on $(hostname)"
echo  "# amodel_env_file : ${amodel_env_file}"
echo  "# if CUDA_PATH is missing : source ${BASH_DIR}/nvidia/loadEnv/loadEnv_build_farm_cask6_sm100_amodel.sh"
echo "# export file        : ${tmp_log_path}  "
echo "# generated by       : ${BASH_SOURCE[0]}:$LINENO  "
echo "# dev source cfg     : ${amodel_env_file}"
echo

dumpinfo  "general env:"
echo  "PYTHON3_PATH         : ${PYTHON3_PATH}"
echo  "PYTHONPATH           : ${PYTHONPATH//:/\\r\\n                       }"
echo  "PYTHONPYCACHEPREFIX  : ${PYTHONPYCACHEPREFIX}"

echo
dumpinfo  "dkg llvm mlir env:"
echo  "LLVM_PATH            : ${LLVM_PATH}"
echo  "LLVM_DIR             : ${LLVM_DIR}"
echo  "MLIR_DIR             : ${MLIR_DIR}"

echo
dumpinfo  "amodel env:"
echo  "CUDA_AMODEL_REVISION : ${CUDA_AMODEL_REVISION}"
echo  "CUDA_DRIVER_REVISION : ${CUDA_DRIVER_REVISION}"
echo  "CUDA_REVISION        : ${CUDA_REVISION}"

echo  "CUDA_AMODEL_GPU      : ${CUDA_AMODEL_GPU}"
echo  "CUDA_A_DRIVER_DIR    : ${CUDA_A_DRIVER_DIR}"
echo  "CUDA_AMODEL_DLL      : ${CUDA_AMODEL_DLL}"
echo  "CUDA_AMODEL_DIR      : ${CUDA_AMODEL_DIR}"
echo  "AMODEL_CONFIG_DIR    : ${AMODEL_CONFIG_DIR}"
echo  "AMODEL_LOG_DIR       : ${AMODEL_LOG_DIR}"
echo  "EXT_DIR          : ${EXT_DIR}"
echo  "AMODEL_DIR           : ${AMODEL_DIR}"
echo  "AMODEL_OVERRIDE_DEFAULT_KNOB_FILE    : ${AMODEL_OVERRIDE_DEFAULT_KNOB_FILE}"

echo
dumpinfo  "build env:"
echo  "# https://gitlab-master.nvidia.com/dlarch-fastkernels/cutlass/-/blob/dev/bloom/testing/test_configuration/amodel/sm100/amodel_env.json "
echo  "CMAKE_PATH           : ${CMAKE_PATH}"
echo  "CXX_PATH             : ${CXX_PATH}"
echo  "CC                   : ${CC}"
echo  "CXX                  : ${CXX}"
# echo  "CUDACXX              : ${CUDACXX}"                    # should be : ${CUDA_PATH}/bin/nvcc
echo  "CUDA_DRIVER_DIR      : ${CUDA_DRIVER_DIR}"
echo  "CUDA_PATH            : ${CUDA_PATH}"
echo  "CUDNN_PATH           : ${CUDNN_PATH}"
echo  "LIBRARY_PATH         : ${LIBRARY_PATH//:/\\r\\n                       }"

echo
dumpinfo  "run env:"
echo  "LD_PRELOAD           : ${LD_PRELOAD//:/\\r\\n                       }"
# echo  "LD_LIBRARY_PATH      : ${LD_LIBRARY_PATH}"
# echo  "PATH                 : ${PATH}"
echo  "LD_LIBRARY_PATH      : ${LD_LIBRARY_PATH//:/\\r\\n                       }"
echo  "PATH                 : ${PATH//:/\\r\\n                       }"

bash_script_o
) | grep -v "0;0m" >| ${tmp_log_path}

dumpinfo ${tmp_log_path}

[[ "$(pwd -L)/cmds/ienv_$envMode.ini" != "${tmp_log_path_def}" ]] && cat ${tmp_log_path}
