

datetime=$(date '+%Y%m%d_%H%M%S')
pid=$$

logfile="${EXT_DIR}/myReference/log_example/gdb/gdb_log_${pid}_${datetime}.txt"
hisfile="${EXT_DIR}/myReference/log_example/gdb/gdb_history_${pid}_${datetime}.txt"
echo "" >| "${logfile}"
echo "" >| "${hisfile}"

tmp_gdb_cmd_file="${EXT_DIR}/tmp/cache/gdb_tmp/gdb_log_file.gdb"
[[ -f "${tmp_gdb_cmd_file}" ]] && rm "${tmp_gdb_cmd_file}"
{
    echo "# generated by : ${BASH_SOURCE[0]}:$LINENO "
    echo "echo echo \\r\\n+++++++++ loading ${tmp_gdb_cmd_file} ...\\r\\n"
    echo " "
    echo "set logging file $logfile"
    echo "set logging overwrite on"
    # echo "set logging on"       # old gdb version
    echo "# set logging enabled on"
    echo "show logging"
    echo " "    
    echo "set history expansion"
    echo "set history filename $hisfile"
    echo "set history save on"
    echo ""
    echo "echo echo \\r\\n--------- leaving ${tmp_gdb_cmd_file} ...\\r\\n"
} | tee "${tmp_gdb_cmd_file}"
echo "" >> "${tmp_gdb_cmd_file}"


sleep 1s

