bash_script_i
echo

tmp_log_dir="${TEMP_DIR}/to_del/script_log"
if [[ ! -d "${tmp_log_dir}/" ]]; then
    mkdir -p "${tmp_log_dir}"
fi

log_path="${tmp_log_dir}/tester_run_`date "+%Y%m%d_%H%M"`.log"
python3  $*     2>&1   |  tee          ${log_path}
echo "  "                                                                       >>  ${log_path}
echo " # generated by  ${BASH_SOURCE[0]}:$LINENO "                              >>  ${log_path}
echo "${blue}Done : $1  ${end}"
echo "${green}log  : ${log_path}  ${end}"

echo
bash_script_o