#!/bin/bash
# [ 2025-07-06 10:34:51 ] auto-generated by /home/xlshen/scratch/bash_env/setup.sh:25
# It contains the path configuration for bash environment.
[[ ! -v disable_bash_script_io ]] && echo -e "# +++++++++ loading ${BASH_SOURCE[0]}:${LINENO}  \e[0;30m:  ${BASH_SOURCE[1]##*/}:${BASH_LINENO[0]} \e[0;0m" 

export EXT_DIR="/home/xlshen/scratch"
export BASH_DIR="/home/xlshen/scratch/bash_env"
export TEMP_DIR="/home/xlshen/scratch/tmp"
export BACKUP_DIR="/home/xlshen/scratch/backup"
export CACHE_DIR="/home/xlshen/scratch/cache"
export TEST_DIR="/home/xlshen/scratch/test"

[[ ! -v disable_bash_script_io ]] && echo -e "# --------- leaving ${BASH_SOURCE[0]}:${LINENO}  "
